# -*- coding: utf-8 -*-
"""week 1 assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NInE-RY67zCvJ2DuiQug0RWOXQUAckN
"""



crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3/10
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6/10
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8/10
    }
}

crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3/10
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6/10
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8/10
    }
}

def get_crypto_advice(user_query):
    user_query = user_query.lower()

    if "sustainable" in user_query:
        recommend = max(crypto_db, key=lambda x: crypto_db[x]["sustainability_score"])
        print(f"Invest in {recommend}! 🌱 It's eco-friendly and has long-term potential!")
    elif "trending" in user_query:
        profitable_coins = [coin for coin, data in crypto_db.items() if data['price_trend'] == 'rising' and data['market_cap'] == 'high']
        if profitable_coins:
            print(f"🚀 Invest in {profitable_coins[0]}! It's trending up and has a high market cap!")
        else:
            print("No high-trending, high-market-cap coins found in current data!")
    elif "long-term" in user_query:
        sustainable_coins = [coin for coin, data in crypto_db.items() if data['energy_use'] == 'low' and data['sustainability_score'] > 7/10]
        if sustainable_coins:
            print(f"For long-term growth, consider {sustainable_coins[0]}! 🌿💼")
        else:
            print("No highly sustainable coins found for long-term investment!")
    else:
        print("Could you please specify what you're looking for in a cryptocurrency?")
get_crypto_advice("which crypto is trending up?")
get_crypto_advice("what's the most sustainable coin?")